MKSHELL=/bin/bash

# Pre-process reads.
# ====================
# Pre-process PAIRED END reads from a pair of compressed fastq file.
#
%_R1.paired.fastq.gz:Q: %_R1.fastq.gz %_R2.fastq.gz
	echo "[DEBUG] trimm reads from $prereq"
	java -jar trimmomatic-0.39.jar \
		PE \
		-trimlog $stem.trimlog.txt \
		$prereq \
		$stem'_R1.paired.fastq.gz' \
		$stem'_R1.unpaired.fastq.gz' \
		$stem'_R2.paired.fastq.gz' \
		$stem'_R2.unpaired.fastq.gz' \
		ILLUMINACLIP:all_adapters_v0.38.fa:2:30:10 \
		AVGQUAL:$trim_avgqual \
		LEADING:$trim_leading \
		TRAILING:$trim_trailing \
		SLIDINGWINDOW:$trim_slide_size:$trim_slide_qual \
		MINLEN:$trim_minlen
