MKSHELL="/bin/bash"

all_samples_trim_report.pdf:Q: all_samples_trim_report.tsv
	echo "[DEBUG] create the Rmd report"
  Rscript --vanilla runthermd.R $target

all_samples_trim_report.tsv:Q:
	echo "[DEBUG] create the TSV report"
	# create header
	echo "sample original pair_survived fwd_only rev_only dropped" | tr " " "\t" > $target
	for ifile in $(find -L . -type f -name "*.trimreport.txt")
	do
		sample=$(basename $ifile .trimreport.txt)
		infoline=$(grep "Input Reads" $ifile)
		inputreads=$(echo $infoline | cut -d" " -f3)
		pairsurvived=$(echo $infoline | cut -d" " -f5)
		forwardonly="0"
		reverseonly="0"
		dropped=$(echo $infoline | cut -d" " -f8)
		echo "$sample $inputreads $pairsurvived $forwardonly $reverseonly $dropped" | tr " " "\t" >> $target
	done
