MKSHELL=/bin/bash

# Pre-process reads.
# ====================
# Pre-process PAIRED END reads from a pair of compressed fastq file.
#
%.trimreport.txt:Q: %.fastq.gz
	echo "[DEBUG] trimm reads from $prereq"
	java -jar trimmomatic-0.39.jar \
		SE \
		-trimlog $stem.trimlog.txt \
		$prereq \
		$stem'.trimmed.fastq.gz' \
		ILLUMINACLIP:all_adapters_v0.38.fa:2:30:10 \
		AVGQUAL:$TRIM_AVGQUAL \
		LEADING:$TRIM_LEADING \
		TRAILING:$TRIM_TRAILING \
		SLIDINGWINDOW:$TRIM_SLIDE_SIZE:$TRIM_SLIDE_QUAL \
		MINLEN:$TRIM_MINLEN 2> $target
